blogproject/advito/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, 
    PasswordResetConfirmView, PasswordResetCompleteView
)
from . import views
from . import views_auth

app_name="advito"

urlpatterns = [
    url(r'index/', views.IndexView.as_view(), name='index'),
    path('support/', views.support, name='support'),
    path('category/<int:category_id>/', views.category_post, name='category_post'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'), 
    path('post/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:post_id>/edit/', views.PostEditView.as_view(), name='post_edit'), 
    path('post/<int:post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:post_id>/delete_success/', TemplateView.as_view(
        template_name='advito/delete_success.html'
    ), name='post_delete_success'),
    path('post/<int:post_id>/message/', views.PostCreateMessageView.as_view(), name='post_message'),
    path('post/<int:post_id>/message/<int:message_id>/', views.PostCreateMessageView.as_view(), name='post_message_reply'),
    path('post/<int:post_id>/review/', views.ReviewCreateView.as_view(), name='review'),
    
    # views_auth

    path('<int:user_id>/profile/', views_auth.ProfileView.as_view(), name='profile'), 
    path('<int:user_id>/profile/update', views_auth.UpdateProfileView.as_view(), name='profile_update'),
    path('<int:user_id>/profile/posts/', views_auth.profile_posts, name='profile_posts'),
    path('<int:user_id>/profile/messages/', views_auth.ProfileMessageView.as_view(), name='profile_message'),
    path('<int:user_id>/profile/reviews/', views_auth.profile_review, name='profile_review'),
    path('<int:user_id>/profile/message_to/', views_auth.MessageToProfileView.as_view(), name='message_to_profile'),
    path('<int:user_id>/profile/review_to/', views_auth.review_to_profile, name='review_to_profile'),
    path('<int:user_id>/profile/comments/', views_auth.ProfileCommentView.as_view(), name='profile_comment'),
    path('<int:user_id>/profile/posts/favorite', views.FavoritePostView.as_view(), name='favorite_post'),  

    path('login/', views_auth.Login.as_view(), name='login'),
    path('logout/', views_auth.logout_views, name='logout'),
    path('signup/', views_auth.SignUpView.as_view(), name='signup'),

    path('password_reset/', PasswordResetView.as_view(
        success_url=reverse_lazy('advito:password_reset_done'),
        template_name='my_auth/password_reset.html',
        email_template_name='my_auth/password_reset_email.html',
    ), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='my_auth/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset/<str:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('advito:password_reset_complete'),
        template_name='my_auth/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='my_auth/password_reset_complete.html'
    ), name='password_reset_complete'),
]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from blogproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advito.main_urls')),
    path('advito/', include('advito.urls')),
]

# STATIC_URLS
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# MEDIA_URLS
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# STATIC_URL - путь статичных файлов
# STATIC_ROOT - в какой папке находятся статичные файлы
# Функцией static регистрирует все пути

blogproject/advito/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import Post, Comment, Message, Review


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ['category', 'price', 'name_descript','description', 'image']

        labels = {
            'category':'Выберите категорию',
            'price': 'Укажите цену',
            'name_descript':'Заголовок поста',
            'description': 'Описание поста',
            'image':'Выберите файл',
        }

        widjets = {
            'category':forms.Textarea(attrs={
                'class': 'form__category', 
                'placeholder': 'Описание поста',
            }),
            'price':forms.Textarea(attrs={
                'class': 'form__textarea', 
                'placeholder': 'Цена',
            }),
            'name_descript':forms.Textarea(attrs={
                'class': 'form__title', 
                'placeholder': 'Название поста',
            }),
            'description':forms.Textarea(attrs={
                'class': 'form__text', 
                'placeholder': 'Описание поста',
            }),
            'image':forms.ClearableFileInput(attrs={
                'class': 'form__file', 
                'type': 'file',
            }),
        }


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment

        fields =['text']

        labels = {
            'text': 'Оставьте комментарий'
        }

        widjets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст комментария'
            })
        } 

class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Message

        fields =['text']

        labels = {
            'text': 'Текст сообщения',
        }

        widjets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст сообщения'
            }),
        } 

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review

        fields =['rating', 'text']

        labels = {
            'text': 'Оставьте комментарий'
        }

        widjets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст комментария'
            }),
            'rating': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'рейтинг',
            }),
        }

blogproject/advito/views.py
from django.contrib.auth import login, authenticate
from django.core.exceptions import PermissionDenied
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Sum
from django.views.generic import (View, ListView, 
    CreateView, DeleteView, UpdateView, DetailView
)
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q
from .models import (Post, Comment, Profile, 
    CategoryPost, FavoritePost, Review, Message
)
from .forms import (PostForm, CommentForm, 
    MessageForm, ReviewForm
)


def users_counter():
    users =  Profile.objects.all()
    return len(users)


def paginate(posts, request):
    paginate_by = 6
    paginator = Paginator(posts, paginate_by)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    return page, is_paginated, prev_url, next_url


class IndexView(ListView):
    posts = Post.objects.all()
    categories = CategoryPost.objects.all()
    model = Post 
    template_name = 'advito/index.html'
    context_object_name ='posts'
    users_counter = users_counter()
    text = "Зарегистрировано: "

    def get(self, request):
        search_query = self.request.GET.get('q')
        if search_query:
            posts = Post.objects.filter(
                Q(name_descript__icontains=search_query) 
                | Q(description__icontains=search_query)
            )
        else:
            posts = Post.objects.all()

        page, is_paginated, prev_url, next_url = paginate(posts, request)

        context = {
            'page_object': page,
            'categories': self.categories,
            'users_counter': users_counter,
            'text': self.text,
            'is_paginated': is_paginated,
            'prev_url': prev_url,
            'next_url': next_url,
        }

        return render(request, self.template_name, context)


def support(request):
    template_name = 'advito/support.html'
    return render(request, template_name)


class PostDetailView(DetailView):
    categories = CategoryPost.objects.all()
    extra_context = {'categories':categories, }
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_detail.html'
    comment_form_class = CommentForm
    context = {}
    
    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        profile = Profile.objects.get(user=self.object.author)
        context = self.get_context_data(object=self.object)
        context['profile'] = profile
        context['comments'] = Comment.objects.filter(in_post__id=post_id).order_by('-date_publish')

        if request.user.is_authenticated:
            context['comment_form'] = self.comment_form_class()

        return self.render_to_response(context)
        
    @method_decorator(login_required(login_url='/advito/login/'))
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        form = self.comment_form_class(request.POST)

        if form.is_valid():
            print("Форма валидна!")
            comment = form.save(commit=False)
            comment.author = request.user
            comment.in_post = post
            comment.save()
            return redirect(request.META.get('HTTP_REFERER'), request)
        
        elif 'button_add_post' in request.POST:
            if request.user.user_profile:
                favpost_add, created = FavoritePost.objects.get_or_create(
                    post=post, 
                    author=request.user.user_profile
                )
                return redirect(request.META.get('HTTP_REFERER'), request)
        else:
            print("Форма не валидна!")
            return render(request, self.template_name, context={
                'comment_form': self.comment_form_class,
                'post': post,
                'comments': Comment.objects.filter(in_post__id=post_id).order_by('-date_publish')
            })


class PostEditView(UpdateView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_edit.html'
    form_class = PostForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != request.user:
            raise PermissionDenied ("Вы не автор этого поста!!!")
        
        return super(PostEditView, self).dispatch(request, *args, **kwargs)
    
    def get_success_url(self):
        post_id = self.kwargs[self.pk_url_kwarg]
        return reverse('advito:post_detail', args=(post_id, ))


class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'advito/post_create.html'
    
    @method_decorator(login_required(login_url='/advito/login/'))
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        context = {}
        if form.is_valid():
            print("Форма валидна!")
            post_form = form.save(commit=False) 
            post_form.author = request.user 
            post_form.save()
            post_new_id = post_form.id
            post_new = Post.objects.get(id=post_new_id)
            context['post_was_created'] = True
            context['post_new'] = post_new
        else:
            print("Форма не валидна")
            context['post_with_errors'] = True
            context['form'] = form
        
        return render(request, self.template_name, context)


class PostDeleteView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_delete.html'

    # переопределим метод (получение ссылки advito:post_delete_success)
    def get_success_url(self):
        post_id = self.kwargs[self.pk_url_kwarg]
        return reverse('advito:post_delete_success', args=(post_id, ))


class FavoritePostView(ListView):
    model = FavoritePost
    post_form_class = PostForm
    categories = CategoryPost.objects.all()
    template_name = 'advito/favorite_post.html'
    context_object_name ='add_posts'
    extra_context = {'categories':categories, }
    context = {}

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return self.model.objects.filter(
                post__date_pub__year=2021, 
                author=self.request.user.user_profile
            ).order_by('-post__date_pub')[:15]
        else:
            return []

    def post(self, request, *args, **kwargs):
        post_id = request.POST.get('post_id')
        if 'button_dell_post' in request.POST:
            if request.user.user_profile:
                fav_post_delete = Post.objects.get(pk=post_id)
                FavoritePost.objects.filter(post=fav_post_delete).delete()

        return redirect(request.META.get('HTTP_REFERER'), request)


def category_post(request, category_id):
    counter = users_counter()
    posts = Post.objects.filter(category=category_id, date_pub__year=2021)
    categories= CategoryPost.objects.all()
    template_name = 'advito/index.html'
    text = "Зарегистрировано: "
    page, is_paginated, prev_url, next_url = paginate(posts, request)
    
    context = {
        'page_object': page,
        'categories': categories,
        'text': text,
        'users_counter': counter,
        'is_paginated': is_paginated,
        'prev_url': prev_url,
        'next_url': next_url,
    }
    
    return render(request, template_name, context)


class PostCreateMessageView(CreateView):
    model = Post
    pk_url_kwarg = 'post_id'
    categories = CategoryPost.objects.all()
    extra_context = {'categories':categories, }
    form_class = MessageForm
    template_name = 'advito/post_message.html'
    object = None

    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['name_descript'] = self.object.name_descript
        if request.user.is_authenticated:
            context['message_form'] = self.form_class()

        message_id = kwargs.get('message_id', None)
        if not message_id:
            context['author'] = self.object.author
        else:
            message = get_object_or_404(Message, id=message_id)
            context['author'] = message.author

        return self.render_to_response(context)

    @method_decorator(login_required(login_url='/advito/login/'))
    def post(self, request, post_id, message_id=None, *args, **kwargs):
        form = self.form_class(request.POST)
        self.object = self.get_object()
        context = {}
        
        if form.is_valid():
            print("Форма валидна!")
            message = form.save(commit=False)
            message.in_post = self.object
            message.author = request.user.user_profile

            if not message_id:
                message.to_whom = self.object.author
            else:
                replied_message = get_object_or_404(Message, pk=message_id)
                message.to_whom = replied_message.author.user

            message.save()
            context['author'] = self.object.author
            context['message_was_created'] = True
        else:
            print("Форма не валидна")
            context['message_with_errors'] = True
            context['form'] = form
        
        return render(request, self.template_name, context)


class ReviewCreateView(CreateView):
    review_form_class = ReviewForm
    model = Post 
    pk_url_kwarg = 'post_id'

blogproject/advito/templates/advito/base_advito.html
{% extends 'base.html' %}

blogproject/advito/templates/advito/delete_success.html
{% extends 'base.html' %}
{% block content %}
    <h1>Пост удален</h1>
    <a class="button__href" href="{% url 'advito:index' %}">Вернуться на главную</a> ИЛИ
    <a class="button__href" href="{% url 'advito:post_create' %}">Создать новый пост</a>
{% endblock  %}

blogproject/advito/templates/advito/favorite_post.html
{% extends 'base.html' %}
{% block title %}
  Избранное
{% endblock  %}

{% block content %}
  <h1>Избранные объявления</h1>
  <div class="cards">
    {% if add_posts %}    
      <ul class="posts">
        {% for post in add_posts %}
          {% with post=post.post %}
          <li class="post">
            <a href="{% url 'advito:post_detail' post.id %}">
              <h3>{{ post.name_descript }}</h3>
              <p>{{ post.date_pub }}</p>
              <p class="img"><img alt="post image" src="{{ post.image.url }}"></p>
              <p class="price">{{ post.price }} pуб.</p>
              <p class="text">{{ post.description | truncatewords:5 }}</p>
            </a>
            <form class="form-delete" method="POST">
              {% csrf_token %}
              <input style="display: none;" type="text" name="post_id" value="{{ post.id }}">
              <button class="button" type="submit" name="button_dell_post">Удалить избранное</button>
            </form>
          </li>
          {% endwith %}
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endblock  %}

blogproject/advito/templates/advito/index.html
{% extends 'advito/base_advito.html' %}
{% block content %}
  <div class="cards">
    {% if page_object %}
      <ul class="posts">
        {% for post in page_object.object_list %}
          <li class="post">
            <a href="{% url 'advito:post_detail' post.id %}">
              <h3>{{ post.name_descript }}</h3>
              <p>{{ post.date_pub }}</p>
              <p class="post__img"><img class="img" alt="post image" src="{{ post.image.url }}"></p>
              <p class="post__price">{{ post.price }} pуб.</p>
              <p class="post__text">{{ post.description | truncatewords:5 }}</p>
            </a>
          </li>
        {% endfor %}
      </ul>
    {% elif not page_object %}
      <h2>Извините по вашему запросу ничего не найдено :-(</h2>
    {% else %}
      <h2>Постов еще нет</h2>
    {% endif %}
    </div>
{% endblock  %}

blogproject/advito/templates/advito/post_create.html
{% extends 'advito/base_advito.html' %}
{% block title %}
  Создание поста
{% endblock  %}

{% block content %}
  <form class="post-create" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    {% if post_was_created or post_with_errors %}
      <button class="create-post__button" style="display:none" type="submit">Создать пост</button>
    {% else %}
      <button class="create-post__button" type="submit">Создать пост</button>
    {% endif %}
  </form>

  {% if post_with_errors %}
    <p>Исправьте ошибки</p>
  {% endif %}

  {% if post_was_created %}
    <h2>Пост успешно создан!</h2>
    <a href="/advito/post/{{ post_new.id }}">Перейти к созданному посту</a>
  {% endif %}
  
{% endblock  %}

blogproject/advito/templates/advito/post_delete.html
{% extends 'base.html' %}

{% block content %}
  {% if post.author != user %}
    <h1 class="msg">Удалить данный пост может только его автор!!!</h1>
  {% else %}
    <h1 class="msg"> Вы уверенны что хотите удалить этот пост?</h1>
    <form class="form-delete" method="POST" action="{% url 'advito:post_delete' post.id %}">
      {% csrf_token %}
      <button class="button" type="submit">Удалить</button>
    </form>
    <a class="button" href="{% url 'advito:post_detail' post.id %}">Нет</a>
  {% endif %}
{% endblock %}

blogproject/advito/templates/advito/post_detail.html
{% extends 'advito/base_advito.html' %}
{% block title %}
  {{ post.name_descript }}-{{ block.super }}
{% endblock  %}

{% block content %}
  <div class="post-detail-main">
    <div class="post-detail">
      <h1>{{ post.name_descript }}</h1>
      <p>Автор: {{ post.author }}</p>

      {% if post.author != user %}
        <p><a class="message-button" href="{% url 'advito:review' post.id %}">Отзывы о продавце</a></p>
      {% endif %}

      <p>{{ post.date_pub }}</p>
      <img class="img" alt="post image" src="{{ post.image.url }}">
    </div>
    <div class="post-detail post-detail__info"> 
      <p class="price">Цена: {{ post.price }} pуб.</p>
      <p class="text">{{ post.description }}</p>
      <p>Телефон: {{ profile.phone }}</p>

      {% if post.author != user %}
        <p><a class="message-button" href="{% url 'advito:post_message' post.id %}">Написать сообщение</a></p>
        <form class="add-favorite__form" method="POST">
          {% csrf_token %}
          <button class="add-vaforite-button" type="submit" name="button_add_post">Добавить в избранное</button>
        </form>
      {% endif %}

      {% if post.author == user %}
        <p><a class="del-post-button" href="{% url 'advito:post_edit' post.id %}">Редактировать пост</a></p>
        <p><a class="del-post-button" href="{% url 'advito:post_delete' post.id %}">Удалить пост</a></p>
      {% endif %}
    </div>
  </div>
  {% if post.author != user %}
    <div class="comments">
      <h2>Комментарии к посту:</h2>
      {% if comments %}
        <ul>
          {% for comment in comments %}
            <li>
              <p>Автор: <a href="#">{{ comment.author }}</a></p>
              <p>{{ comment.date_publish }}</p>
              <p>{{ comment.text }}</p>
              <hr>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p><i>Пока комментариев нет</i></p>
      {% endif %}
      <form class="comment__form" method="POST">
        {% csrf_token %}
        {{ comment_form.text }}
        <button class="button" type="submit" name="button_send_coment">Отправить комментарий</button>
      </form>
    </div>
  {% endif %}
{% endblock  %}

blogproject/advito/templates/advito/post_edit.html
{% extends 'base.html' %}
{% block title %}
  Редактирование поста
{% endblock  %}

{% block content %}
  <h1>Редактирование поста</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button" type="submit">Сохранить изменения</button>
  </form>
{% endblock  %}

blogproject/advito/templates/advito/post_message.html
{% extends 'base.html' %}
{% block content %}
  {% if user.is_authenticated %}
    <form class="message__form" method="POST">
      {% csrf_token %}
      <h4>Кому: {{ author }}</h4>
      <h4>Объявление: {{ name_descript }}</h4>
      {{ message_form.text }}<br>
      {% if message_was_created or message_with_errors %}
        <button class="button" style="display:none" type="submit">Отправить сообщение</button>
      {% else %}
        <button class="button" type="submit" name="button_send_message">Отправить сообщение</button>
      {% endif %}
    </form>
  {% else %}
    <h2>Пожалуста Войдите или Зарегистрируйтесь!</h2>
  {% endif %}

  {% if message_with_errors %}
    <p>Исправьте ошибки</p>
  {% endif %}

  {% if message_was_created %}
    <h2>Успешно отправлено!</h2>
  {% endif %}
{% endblock  %}

blogproject/advito/templates/advito/support.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
        Advito support
      {% endblock  %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header class="container-back">
      <div class="container">
        <nav class="navigation">
          <div class="navbar">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="logo" href="{% url 'advito:index' %}">
                  <img src="{% static 'img/icon.png' %}" alt="Иконка сайта">
                </a>
                <span class="help__text">ПОМОЩЬ</span>
              </li>
            </ul>
          </div>
          <div class="navbar">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'advito:index' %}">Главная</a>
              </li>
              {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'advito:login' %}">Вход</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'advito:signup' %}">Зерегистрироваться</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'advito:post_create' %}">Разместить объявление</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        <div class="index-form" data-marker="search-form">
          <div class="form" style="margin-left: 20px; display: flex;">
            <input type="text" placeholder="Поиск" maxlength="100" class="suggest">
            <button class="button-element">
              <span class="button-text">Найти</span>
            </button>
          </div>
          <div class="username">
            <span> Привет:&nbsp</span>
            {% if not user.is_authenticated %}
              <span> Незнакомец(ка)</span>
            {% else %}
            <span>{{ user }};</span>
              <span>&nbsp Редактировать:</span>
              <a class="category__href" href="/advito/{{ user.id }}/profile/">My Profile;</a>
              <a class="profile-exit__href" href="{% url 'advito:logout' %}">Выход</a>
            {% endif %}
          </div>
        </div>
      </div>
    </header>
    <main class="container-back">
      <section class="section container" style="height: 500px;">
        <h1>СЛУЖБА ПОДДЕРЖКИ</h1>
      </section>
    </main>
    <footer class="container-back">
      <div class="footer container">
        <div class="footer-social">
          <h3> Мы в социальных сетях</h3>
          <ul class="footer-social__list">
            <li class="footer-social__item">
              <a class = "footer-social__link" href="https://twitter.com/">
                <svg class="footer__logo-svg" width="18" height="15" viewBox="0 0 18 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M11.3 0.166728C13 -0.333272 14.4 0.366728 15 1.26673C15.7 1.06673 16.4 0.766728 
                  17.1 0.566728C17.1 1.36673 16.6 2.06673 16.2 2.26673C16.9 2.46673 17.5 1.76673 17.5 
                  1.76673C17.3 2.76673 16.5 3.46673 15.9 3.76673C15.7 10.3667 12.6 14.7667 5.5 14.5667C5 
                  14.5667 5.6 14.5667 5 14.5667C4.6 14.5667 0.7 14.1667 0 12.7667C2.3 12.9667 4 12.3667 
                  4.8 11.6667C3.8 11.3667 2 11.1667 1.7 8.76673C2.1 8.86673 2.3 8.96673 3 8.86673C1.8 8.06673 
                  0.4 7.36673 0.5 5.16673C0.8 5.46673 1.6 5.66673 1.9 5.66673C1.2 5.46673 -0.1 2.36673 
                  1 0.866728C2.9 2.66673 4.8 4.36673 8.4 4.56673C8.5 2.26673 9.5 0.766728 11.3 0.166728Z"/>
                </svg>
              </a>
            </li>
            <li class="footer-social__item">
              <a class = "footer-social__link" href="https://www.facebook.com">
                <svg class="footer__logo-svg" width="9" height="19" viewBox="0 0 9 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M6.3 3.4C7.1 3.4 7.9 3.4 8.7 3.4C8.7 2.3 8.7 1.2 8.7 0C7.7 0 6.8 0 5.8 0C2.7 0.2 1.5 2.4 1.9 6.1H0V9.6H2C2 
                  12.7 2 15.8 2 18.9C3.3 18.9 4.6 18.9 5.8 18.9C5.8 15.8 5.8 12.7 5.8 9.6H8.7V6.1H5.8C5.8 5.1 5.8 3.7 6.3 3.4Z"/>
                </svg>
              </a>
            </li>
            <li class="footer-social__item">
              <a class="footer-social__link" href="https://www.youtube.com">
                <svg class="footer__logo-svg" width="20" height="14" viewBox="0 0 20 14" fill="none"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M17.1 0H2.8C1.3 0 0 1.3 0 2.8V11.1C0 12.7 1.3 14 2.8 14H17.1C18.7 
                  14 19.9 12.7 19.9 11.2V2.8C20 1.3 18.7 0 17.1 0ZM7 10.4V3.6L13.8 7L7 10.4Z"/>
                </svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>