blogproject/advito/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, 
    PasswordResetConfirmView, PasswordResetCompleteView
)
from . import views
from . import views_auth

app_name="advito"

urlpatterns = [
    url(r'index/', views.IndexView.as_view(), name='index'),
    path('support/', views.support, name='support'),
    path('category/<int:category_id>/', views.category_post, name='category_post'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'), 
    path('post/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:post_id>/edit/', views.PostEditView.as_view(), name='post_edit'), 
    path('post/<int:post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:post_id>/delete_success/', TemplateView.as_view(
        template_name='advito/delete_success.html'
    ), name='post_delete_success'),
    path('post/<int:post_id>/message/', views.PostCreateMessageView.as_view(), name='post_message'),
    path('post/<int:post_id>/message/<int:message_id>/', views.PostCreateMessageView.as_view(), name='post_message_reply'),
    path('post/<int:post_id>/review/', views.ReviewCreateView.as_view(), name='review'),
    
    # views_auth

    path('<int:user_id>/profile/', views_auth.ProfileView.as_view(), name='profile'), 
    path('<int:user_id>/profile/update', views_auth.UpdateProfileView.as_view(), name='profile_update'),
    path('<int:user_id>/profile/posts/', views_auth.profile_posts, name='profile_posts'),
    path('<int:user_id>/profile/messages/', views_auth.ProfileMessageView.as_view(), name='profile_message'),
    path('<int:user_id>/profile/reviews/', views_auth.profile_review, name='profile_review'),
    path('<int:user_id>/profile/message_to/', views_auth.MessageToProfileView.as_view(), name='message_to_profile'),
    path('<int:user_id>/profile/review_to/', views_auth.review_to_profile, name='review_to_profile'),
    path('<int:user_id>/profile/comments/', views_auth.ProfileCommentView.as_view(), name='profile_comment'),
    path('<int:user_id>/profile/posts/favorite', views.FavoritePostView.as_view(), name='favorite_post'),  

    path('login/', views_auth.Login.as_view(), name='login'),
    path('logout/', views_auth.logout_views, name='logout'),
    path('signup/', views_auth.SignUpView.as_view(), name='signup'),

    path('password_reset/', PasswordResetView.as_view(
        success_url=reverse_lazy('advito:password_reset_done'),
        template_name='my_auth/password_reset.html',
        email_template_name='my_auth/password_reset_email.html',
    ), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='my_auth/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset/<str:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('advito:password_reset_complete'),
        template_name='my_auth/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='my_auth/password_reset_complete.html'
    ), name='password_reset_complete'),
]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from blogproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advito.main_urls')),
    path('advito/', include('advito.urls')),
]

# STATIC_URLS
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# MEDIA_URLS
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# STATIC_URL - путь статичных файлов
# STATIC_ROOT - в какой папке находятся статичные файлы
# Функцией static регистрирует все пути

blogproject/advito/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import Post, Comment, Message, Review


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ['category', 'price', 'name_descript','description', 'image']

        labels = {
            'category':'Выберите категорию',
            'price': 'Укажите цену',
            'name_descript':'Заголовок поста',
            'description': 'Описание поста',
            'image':'Выберите файл',
        }

        widjets = {
            'category':forms.Textarea(attrs={
                'class': 'form__category', 
                'placeholder': 'Описание поста',
            }),
            'price':forms.Textarea(attrs={
                'class': 'form__textarea', 
                'placeholder': 'Цена',
            }),
            'name_descript':forms.Textarea(attrs={
                'class': 'form__title', 
                'placeholder': 'Название поста',
            }),
            'description':forms.Textarea(attrs={
                'class': 'form__text', 
                'placeholder': 'Описание поста',
            }),
            'image':forms.ClearableFileInput(attrs={
                'class': 'form__file', 
                'type': 'file',
            }),
        }


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment

        fields =['text']

        labels = {
            'text': 'Оставьте комментарий'
        }

        widjets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст комментария'
            })
        } 

class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Message

        fields =['text']

        labels = {
            'text': 'Текст сообщения',
        }

        widjets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст сообщения'
            }),
        } 

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review

        fields =['rating', 'text']

        labels = {
            'text': 'Оставьте комментарий'
        }

        widjets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст комментария'
            }),
            'rating': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'рейтинг',
            }),
        }

blogproject/advito/views.py
from django.contrib.auth import login, authenticate
from django.core.exceptions import PermissionDenied
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Sum
from django.views.generic import (View, ListView, 
    CreateView, DeleteView, UpdateView, DetailView
)
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q
from .models import (Post, Comment, Profile, 
    CategoryPost, FavoritePost, Review, Message
)
from .forms import (PostForm, CommentForm, 
    MessageForm, ReviewForm
)


def users_counter():
    users =  Profile.objects.all()
    return len(users)


def paginate(posts, request):
    paginate_by = 6
    paginator = Paginator(posts, paginate_by)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    return page, is_paginated, prev_url, next_url


class IndexView(ListView):
    posts = Post.objects.all()
    categories = CategoryPost.objects.all()
    model = Post 
    template_name = 'advito/index.html'
    context_object_name ='posts'
    users_counter = users_counter()
    text = "Зарегистрировано: "

    def get(self, request):
        search_query = self.request.GET.get('q')
        if search_query:
            posts = Post.objects.filter(
                Q(name_descript__icontains=search_query) 
                | Q(description__icontains=search_query)
            )
        else:
            posts = Post.objects.all()

        page, is_paginated, prev_url, next_url = paginate(posts, request)

        context = {
            'page_object': page,
            'categories': self.categories,
            'users_counter': users_counter,
            'text': self.text,
            'is_paginated': is_paginated,
            'prev_url': prev_url,
            'next_url': next_url,
        }

        return render(request, self.template_name, context)


def support(request):
    template_name = 'advito/support.html'
    return render(request, template_name)


class PostDetailView(DetailView):
    categories = CategoryPost.objects.all()
    extra_context = {'categories':categories, }
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_detail.html'
    comment_form_class = CommentForm
    context = {}
    
    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        profile = Profile.objects.get(user=self.object.author)
        context = self.get_context_data(object=self.object)
        context['profile'] = profile
        context['comments'] = Comment.objects.filter(in_post__id=post_id).order_by('-date_publish')

        if request.user.is_authenticated:
            context['comment_form'] = self.comment_form_class()

        return self.render_to_response(context)
        
    @method_decorator(login_required(login_url='/advito/login/'))
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        form = self.comment_form_class(request.POST)

        if form.is_valid():
            print("Форма валидна!")
            comment = form.save(commit=False)
            comment.author = request.user
            comment.in_post = post
            comment.save()
            return redirect(request.META.get('HTTP_REFERER'), request)
        
        elif 'button_add_post' in request.POST:
            if request.user.user_profile:
                favpost_add, created = FavoritePost.objects.get_or_create(
                    post=post, 
                    author=request.user.user_profile
                )
                return redirect(request.META.get('HTTP_REFERER'), request)
        else:
            print("Форма не валидна!")
            return render(request, self.template_name, context={
                'comment_form': self.comment_form_class,
                'post': post,
                'comments': Comment.objects.filter(in_post__id=post_id).order_by('-date_publish')
            })


class PostEditView(UpdateView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_edit.html'
    form_class = PostForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != request.user:
            raise PermissionDenied ("Вы не автор этого поста!!!")
        
        return super(PostEditView, self).dispatch(request, *args, **kwargs)
    
    def get_success_url(self):
        post_id = self.kwargs[self.pk_url_kwarg]
        return reverse('advito:post_detail', args=(post_id, ))


class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'advito/post_create.html'
    
    @method_decorator(login_required(login_url='/advito/login/'))
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        context = {}
        if form.is_valid():
            print("Форма валидна!")
            post_form = form.save(commit=False) 
            post_form.author = request.user 
            post_form.save()
            post_new_id = post_form.id
            post_new = Post.objects.get(id=post_new_id)
            context['post_was_created'] = True
            context['post_new'] = post_new
        else:
            print("Форма не валидна")
            context['post_with_errors'] = True
            context['form'] = form
        
        return render(request, self.template_name, context)


class PostDeleteView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_delete.html'

    # переопределим метод (получение ссылки advito:post_delete_success)
    def get_success_url(self):
        post_id = self.kwargs[self.pk_url_kwarg]
        return reverse('advito:post_delete_success', args=(post_id, ))


class FavoritePostView(ListView):
    model = FavoritePost
    post_form_class = PostForm
    categories = CategoryPost.objects.all()
    template_name = 'advito/favorite_post.html'
    context_object_name ='add_posts'
    extra_context = {'categories':categories, }
    context = {}

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return self.model.objects.filter(
                post__date_pub__year=2021, 
                author=self.request.user.user_profile
            ).order_by('-post__date_pub')[:15]
        else:
            return []

    def post(self, request, *args, **kwargs):
        post_id = request.POST.get('post_id')
        if 'button_dell_post' in request.POST:
            if request.user.user_profile:
                fav_post_delete = Post.objects.get(pk=post_id)
                FavoritePost.objects.filter(post=fav_post_delete).delete()

        return redirect(request.META.get('HTTP_REFERER'), request)


def category_post(request, category_id):
    counter = users_counter()
    posts = Post.objects.filter(category=category_id, date_pub__year=2021)
    categories= CategoryPost.objects.all()
    template_name = 'advito/index.html'
    text = "Зарегистрировано: "
    page, is_paginated, prev_url, next_url = paginate(posts, request)
    
    context = {
        'page_object': page,
        'categories': categories,
        'text': text,
        'users_counter': counter,
        'is_paginated': is_paginated,
        'prev_url': prev_url,
        'next_url': next_url,
    }
    
    return render(request, template_name, context)


class PostCreateMessageView(CreateView):
    model = Post
    pk_url_kwarg = 'post_id'
    categories = CategoryPost.objects.all()
    extra_context = {'categories':categories, }
    form_class = MessageForm
    template_name = 'advito/post_message.html'
    object = None

    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['name_descript'] = self.object.name_descript
        if request.user.is_authenticated:
            context['message_form'] = self.form_class()

        message_id = kwargs.get('message_id', None)
        if not message_id:
            context['author'] = self.object.author
        else:
            message = get_object_or_404(Message, id=message_id)
            context['author'] = message.author

        return self.render_to_response(context)

    @method_decorator(login_required(login_url='/advito/login/'))
    def post(self, request, post_id, message_id=None, *args, **kwargs):
        form = self.form_class(request.POST)
        self.object = self.get_object()
        context = {}
        
        if form.is_valid():
            print("Форма валидна!")
            message = form.save(commit=False)
            message.in_post = self.object
            message.author = request.user.user_profile

            if not message_id:
                message.to_whom = self.object.author
            else:
                replied_message = get_object_or_404(Message, pk=message_id)
                message.to_whom = replied_message.author.user

            message.save()
            context['author'] = self.object.author
            context['message_was_created'] = True
        else:
            print("Форма не валидна")
            context['message_with_errors'] = True
            context['form'] = form
        
        return render(request, self.template_name, context)


class ReviewCreateView(CreateView):
    review_form_class = ReviewForm
    model = Post 
    pk_url_kwarg = 'post_id'

blogproject/advito/templates/my_auth/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="login-main">
    <div class="login">
      {% if form.errors %}
        {% for field, errors in form.errors.items %}
        <p>{{ errors }}</p>
        {% endfor %}
      {% endif %}
      <h2>Войти</h2>
      {% if not user.is_authenticated %}
        <form class="login__form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
            <p>{{ field }}</p>
            {% if field.errors %}
              <ul>{{ field.errors }}</ul>
            {% endif %}
          {% endfor%}
          <button class="log-button__submit" type="submit" style="margin-top: 20px; width: 120px;">Войти</button>
          <p> ИЛИ </p>
          <a class="button" style="max-width: 170px;" href="{% url 'advito:signup' %}">Зарегистрироваться</a>
        </form>
        <a class="passres__href" href="{% url 'advito:password_reset' %}">Забыли пароль?</a>
      {% else %}
        <h3>Привет, {{ user.username }}</h3>
        <a href="{% url 'advito:logout' %}">Выйти</a>
        <a href="{% url 'advito:index' %}">На главную</a>
      {% endif %}
    </div>
  </div>
{% endblock  %}

blogproject/advito/templates/my_auth/message_to_profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="message-to-profile">
    {% if messages %}
      <ul class="messages-to">
        {% for message in messages %}
          <li class="message">
            <p class="message__name">Объявление: <i class="message__name_text">{{ message.in_post.name_descript }}</i></p>
            <p class="message__name">От кого: <i class="message__name_text">{{ message.author }}</i></p>
            <p class="message__name">Сообщение: <i class="message__name_text">{{ message.text }}</i></p>
            <p class="message__name">Дата: <i class="message__name_text">{{ message.date_pub }}</i></p>
          </li>
          <p><a class="message-button" href="{% url 'advito:post_message_reply' message.in_post.id message.id %}">Ответить</a></p>
          {% comment %} <form method="POST">
            {% csrf_token %}
            <button class="button" type="submit" name="buton-message-del">Удалить сообщение</button>
          </form> {% endcomment %}
          <hr>
        {% endfor %}
      </ul>
    {% else %}
      <i>Пока сообщений нет</i>
    {% endif %}
  </div>
{% endblock  %}

blogproject/advito/templates/my_auth/password_reset.html
{% extends 'base.html' %}
{% block content %}
  <div class="password-reset">
    <h2>Восстановление пароля</h3>
    <hr>
    {% if not user.is_authenticated %}
      <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Восстановить</button>
      </form>
    {% else %}
      <a href="{% url 'core:logout' %}">Выйти</a>
    {% endif %}
  </div> 
{% endblock %}

blogproject/advito/templates/my_auth/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Ваш пароль успешно сброшен!</h2>
{% endblock %}

blogproject/advito/templates/my_auth/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
  <h2>Восстановление пароля</h2>
  <hr>
  {% if validlink %}
    <form action="" method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Изменить пароль</button>
    </form>
  {% else %}
    <h3>Ссылка не валидна</h3>
  {% endif %}
{% endblock %}

blogproject/advito/templates/my_auth/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
  <h2>Проверьте Вашу почту</h3>
{% endblock %}

blogproject/advito/templates/my_auth/password_reset_email.html
{% autoescape off %}
  Для сброса пароля перейдите по ссылке
  {{ protocol }}://{{ domain }}{% url 'advito:password_reset_confirm' uidb64=uid token=token %}
{% endautoescape %}

blogproject/advito/templates/my_auth/profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="profile-user" >
    <h1>{{ profile.user.username }}</h1>
    <ul class=profile-user__item>
      <li>
        <h3>Фото профиля:</h3>
        {% if profile.avatar %}
          <img class="profile__img" src="{{ profile.avatar.url }}">
        {% else %}
          <i>Не заполнено</i>
        {% endif %}
      </li>
      <li>
        <h3>Дата рождения:</h3>
        {% if profile.birth_date %}
          <i>{{ profile.birth_date|date:"d F Y" }} </i>
        {% else %}
        <i>Не заполнено</i>
        {% endif %}
      </li>
      <li>
        <h3>Телефон:</h3>
        {% if profile.phone %}
          <i>{{ profile.phone }}</i>
        {% else %}
          <i>Не заполнено</i>
        {% endif %}
      </li>
      <li>
        <h3>Город:</h3>
        {% if profile.town %}
          <i>{{ profile.town }} </i>
        {% else %}
          <i>Не заполнено</i>
        {% endif %}
      </li>
      <li>
        <h3>Обо мне:</h3>
        {% if profile.about %}
          <i>{{ profile.about }} </i>
        {% else %}
          <i>Не заполнено</i>
        {% endif %}
      </li>
      <li>
        <h3>Посмотреть:</h3>
        {% if user.id == profile.user.id %}
          <a href="{% url 'advito:profile_posts' user.id %}">Мои обьявления;</a>
          <a href="{% url 'advito:favorite_post' user.id %}">Избранные обьявления;</a>
          <a href="{% url 'advito:profile_comment' user.id %}">Мои комментарии;</a>
          <a href="{% url 'advito:profile_message' user.id %}">Мои сообщения;</a>
          <a href="{% url 'advito:profile_review' user.id %}">Мои отзывы;</a>
          <a href="{% url 'advito:review_to_profile' user.id %}">Отзывы обо мне;</a>
          <a href="{% url 'advito:message_to_profile' user.id %}">Сообщения адресованные мне;</a>
        {% endif %}
      </li>
      <li>
        <h3>Редактировать:</h3>
        {% if user.id == profile.user.id %}
          <p><a href="{% url 'advito:profile_update' profile.user.id %}">Мой профиль</a></p>
        {% endif %}
      </li>
    </ul>
  </div>
{% endblock  %}

blogproject/advito/templates/my_auth/profile_comment.html
{% extends 'base.html' %}
{% block content %}
  <div class="profile-comments">
    <h1>Мои комментарии:</h1>
    {% if comments %}
      <ul class="profile-comments">
        {% for comment in comments %}
          <li class="comment">
            <p class="comment__name">Объявление: <i class="comment__name_text">{{ comment.in_post.name_descript }}</i>; 
            Автор: <i>{{ comment.in_post.author }}</i></p>
            <p class="comment__name">Комментарий: <i class="comment__name_text">{{ comment.text }}</i></p>
            <p class="comment__name">Дата: <i class="comment__name_text">{{ comment.date_publish }}</i></p>
          </li>
          {% comment %} <form method="POST">
            {% csrf_token %}
            <input style="display: none;" type="text" name="comment_id" value="{{ comment.id }}">
            <button class="button" type="submit" name="button_dell_comment">Удалить комментарий</button>
          </form> {% endcomment %}
          <hr>
        {% endfor %}
      </ul>
    {% else %}
      <i>Пока комментариев нет</i>
    {% endif %}
    </div>
{% endblock  %}

blogproject/advito/templates/my_auth/profile_message.html
{% extends 'base.html' %}
{% block content %}
  <div class="profile-messages">
    <h1>Мои сообщения:</h1>
    {% if messages %}
      <ul class="prof-messages">
        {% for message in messages %}
          <li class="message">
            <p class="message__name">Объявление: <i class="message__name_text">{{ message.in_post.name_descript }};</i></p>
            <p class="message__name">Кому: <i class="message__name_text">{{ message.to_whom }}</i></p>
            <p class="message__name">Сообщение: <i class="message__name_text">{{ message.text }}</i></p>
            <p class="message__name">Дата: <i class="message__name_text">{{ message.date_pub }}</i></p>
          </li>
          {% comment %} <form method="POST">
            {% csrf_token %}
            <button class="button" type="submit">Удалить сообщение</button>
          </form> {% endcomment %}
          <hr>
        {% endfor %}
      </ul>
    {% else %}
      <i>Пока сообщений нет</i>
    {% endif %}
  </div>
{% endblock  %}

blogproject/advito/templates/my_auth/profile_review.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="profile-reviews">
  <h1>Мои отзывы:</h1>
  {% if reviews %}
    <ul class="prof-reviews">
      {% for review in reviews %}
        <li class="review">
          <p class="review__name">Кому: <i class="review__name_text">{{ review.to_whom }}</i></p>
          <p class="review__name">Кол-во звезд:&nbsp<i class="stars"> {{ review.rating }}</i></p>
          {% if  review.text %}
            <p class="review__name">Отзыв: <i class="review__name_text">{{ review.text }}</i></p>
          {% endif %}
          <p class="review__name">Дата: <i class="review__name_text">{{ review.date_pub }}</i></p>
        </li>
        <hr>
      {% endfor %}
    </ul>
  {% else %}
    <i>Пока отзывов нет</i>
  {% endif %}
  </div>
  <script src="{% static 'js/script.js' %}"></script>
{% endblock  %}

blogproject/advito/templates/my_auth/profile_update.html
{% extends 'base.html' %}
{% block content %}
  <h2>Редактирование профиля:</h2>
    <form class="profile-update__form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        {{ field.label }}
        {{ field }}
        {{ field.errors }}
      {% endfor %}
      <button class="button__submit" type="submit" style="margin-top: 20px; width: 120px;">Сохранить</button>
    </form>
{% endblock  %}

blogproject/advito/templates/my_auth/review_to_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="profile-reviews">
  <h1>Отзывы обо мне:</h1>
  {% if reviews_to %}
    <ul class="prof-reviews">
      {% for review in reviews_to %}
        <li class="review">
          <p class="review__name">От кого: <i class="review__name_text">{{ review.author }}</i></p>
          <p class="review__name">Кол-во звезд:&nbsp<i class="stars"> {{ review.rating }}</i></p>
          {% if review.text %}
            <p class="review__name">Отзыв: <i class="review__name_text">{{ review.text }}</i></p>
          {% endif %}
          <p class="review__name">Дата: <i class="review__name_text">{{ review.date_pub }}</i></p>
        </li>
        {% comment %} <form method="POST">
          {% csrf_token %}
          <button class="button" type="submit">Удалить сообщение</button>
        </form> {% endcomment %}
        <hr>
      {% endfor %}
    </ul>
  {% else %}
    <i>Пока отзывов нет</i>
  {% endif %}
  </div>
  <script src="{% static 'js/script.js' %}"></script>
{% endblock  %}

blogproject/advito/templates/my_auth/signup.html
{% extends 'base.html' %}
{% block content %}
  <div class="signup-main">
    <div style="padding: 20px;">
      <h2>Регистрация</h2>
      {% if not registered %}
        <form class="signup__form" method="POST">
          {% csrf_token %}
          {% for field in form %}
            <p>{{ field }}</p>
            {% if field.errors %}
              <ul>{{ field.errors }}</ul>
            {% endif %}
          {% endfor%}
          <button class="button__submit" type="submit" style="margin-top: 20px; width: 120px;">Продолжить</button>
        </form>
      {% else %}
        <h2>Вы успешно зарегистрированы</h2>
        <a class="reg__link" href="{% url 'advito:login' %}" class="link">Войти</a>
      {% endif %}
    </div>
  </div> 
{% endblock %}