blogproject/advito/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, 
    PasswordResetConfirmView, PasswordResetCompleteView
)
from . import views
from . import views_auth

app_name="advito"

urlpatterns = [
    url(r'index/', views.IndexView.as_view(), name='index'),
    path('support/', views.support, name='support'),
    path('category/<int:category_id>/', views.category_post, name='category_post'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'), 
    path('post/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:post_id>/edit/', views.PostEditView.as_view(), name='post_edit'), 
    path('post/<int:post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:post_id>/delete_success/', TemplateView.as_view(
        template_name='advito/delete_success.html'
    ), name='post_delete_success'),
    path('post/<int:post_id>/message/', views.PostCreateMessageView.as_view(), name='post_message'),
    path('post/<int:post_id>/message/<int:message_id>/', views.PostCreateMessageView.as_view(), name='post_message_reply'),
    path('post/<int:post_id>/review/', views.ReviewCreateView.as_view(), name='review'),
    
    # views_auth

    path('<int:user_id>/profile/', views_auth.ProfileView.as_view(), name='profile'), 
    path('<int:user_id>/profile/update', views_auth.UpdateProfileView.as_view(), name='profile_update'),
    path('<int:user_id>/profile/posts/', views_auth.profile_posts, name='profile_posts'),
    path('<int:user_id>/profile/messages/', views_auth.ProfileMessageView.as_view(), name='profile_message'),
    path('<int:user_id>/profile/reviews/', views_auth.profile_review, name='profile_review'),
    path('<int:user_id>/profile/message_to/', views_auth.MessageToProfileView.as_view(), name='message_to_profile'),
    path('<int:user_id>/profile/review_to/', views_auth.review_to_profile, name='review_to_profile'),
    path('<int:user_id>/profile/comments/', views_auth.ProfileCommentView.as_view(), name='profile_comment'),
    path('<int:user_id>/profile/posts/favorite', views.FavoritePostView.as_view(), name='favorite_post'),  

    path('login/', views_auth.Login.as_view(), name='login'),
    path('logout/', views_auth.logout_views, name='logout'),
    path('signup/', views_auth.SignUpView.as_view(), name='signup'),

    path('password_reset/', PasswordResetView.as_view(
        success_url=reverse_lazy('advito:password_reset_done'),
        template_name='my_auth/password_reset.html',
        email_template_name='my_auth/password_reset_email.html',
    ), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='my_auth/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset/<str:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('advito:password_reset_complete'),
        template_name='my_auth/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='my_auth/password_reset_complete.html'
    ), name='password_reset_complete'),
]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from blogproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advito.main_urls')),
    path('advito/', include('advito.urls')),
]

# STATIC_URLS
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# MEDIA_URLS
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# STATIC_URL - путь статичных файлов
# STATIC_ROOT - в какой папке находятся статичные файлы
# Функцией static регистрирует все пути

blogproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
	  <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
        Advito
      {% endblock  %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
  </head>
  <body>
    <header class="container-back">
      <div class="container">
        <nav class="navigation">
          <div class="container-nav">
            <div class="navbar">
              <ul class="navbar-nav">
                <li class="nav-item">
                <a class="logo" href="{% url 'advito:index' %}">
                  <img class="logo__img" src="{% static 'img/icon.png' %}" alt="Иконка сайта">
                </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'advito:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">О нас</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/advito/support/">Помощь</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="navbar">
            <ul class="navbar-nav">
              {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'advito:login' %}">Вход</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'advito:signup' %}">Зерегистрироваться</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'advito:post_create' %}">Разместить объявление</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        <div class="index-form" data-marker="search-form">
          <div class="category">
            <div class="category-select">
              <select id="my_select" name="category_id" class="select" style="height: 27px;" onchange="getData(this)">
                <option selected="selected" disabled>Выберите категорию...</option>
                <option class="category-select" value="#" href="/advito/index">Все категории</option>
                {% for category in categories %}
                  <option class="category-select" value="{{ category.id }}" 
                    href="/advito/category/{{ category.id }}">
                    {{ category.name_category }}
                  </option>
                {% endfor %}
              </select>
            </div>
          </div>
          <form class="form_search" action="{% url 'advito:index' %}" method="get">
            <input name="q" type="search" placeholder="Поиск по объявлениям...">
            <button class="button-text">Найти</button>
          </form>
          <div class="username">
            <span> Привет:&nbsp</span>
            {% if not user.is_authenticated %}
              <span> Незнакомец(ка)</span>
            {% else %}
              <span>{{ user }};</span>
              <span>&nbsp Редактировать: &nbsp</span>
              <a class="profile__href" href="{% url 'advito:profile' user.id %}">My Profile;</a>
              <a class="profile-exit__href" href="{% url 'advito:logout' %}">Выход</a>
            {% endif %}
          </div>
        </div>
        <i class="users_counter">{{ text }}{{ users_counter }}</i>
    </div>
  </header>

    <main class="container-back">
      <section class="section container">
        {% block content %}
        Ther is no any content
        {% endblock  %}
        {% if is_paginated %}
          <div class="pages">
            <ul class="pagination">
              <li class="page__item {% if not prev_url %} disabled {% endif %}">
                <a class="pages__link pages__link_active" href="{{ prev_url }}">Предыдущая</a>
              </li>
              {% for n in page_object.paginator.page_range %}
                {% if page_object.number == n %}
                  <li class="page__item active">
                    <a class="pages__link" href="?page={{ n }}">{{ n }}</a>
                  </li>
                {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
                  <li class="page__item">
                    <a class="pages__link" href="?page={{ n }}">{{ n }}</a>
                  </li>
                {% endif %}
              {% endfor %} 
              <li class="page__item {% if not next_url %} disabled {% endif %}">
                <a class="pages__link" href="{{ next_url }}">Следующая</a>
              </li>
            </ul>
          </div>
        {% endif %}
      </section>
    </main>

    <footer class="container-back">
      <div class="footer container">
        <div class="footer-social">
          <h3> Мы в социальных сетях</h3>
          <ul class="footer-social__list">
            <li class="footer-social__item">
              <a class = "footer-social__link" href="https://twitter.com/">
                <svg class="footer__logo-svg" width="18" height="15" viewBox="0 0 18 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M11.3 0.166728C13 -0.333272 14.4 0.366728 15 1.26673C15.7 1.06673 16.4 0.766728 
                  17.1 0.566728C17.1 1.36673 16.6 2.06673 16.2 2.26673C16.9 2.46673 17.5 1.76673 17.5 
                  1.76673C17.3 2.76673 16.5 3.46673 15.9 3.76673C15.7 10.3667 12.6 14.7667 5.5 14.5667C5 
                  14.5667 5.6 14.5667 5 14.5667C4.6 14.5667 0.7 14.1667 0 12.7667C2.3 12.9667 4 12.3667 
                  4.8 11.6667C3.8 11.3667 2 11.1667 1.7 8.76673C2.1 8.86673 2.3 8.96673 3 8.86673C1.8 8.06673 
                  0.4 7.36673 0.5 5.16673C0.8 5.46673 1.6 5.66673 1.9 5.66673C1.2 5.46673 -0.1 2.36673 
                  1 0.866728C2.9 2.66673 4.8 4.36673 8.4 4.56673C8.5 2.26673 9.5 0.766728 11.3 0.166728Z"/>
                </svg>
              </a>
            </li>
            <li class="footer-social__item">
              <a class = "footer-social__link" href="https://www.facebook.com">
                <svg class="footer__logo-svg" width="9" height="19" viewBox="0 0 9 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M6.3 3.4C7.1 3.4 7.9 3.4 8.7 3.4C8.7 2.3 8.7 1.2 8.7 0C7.7 0 6.8 0 5.8 0C2.7 0.2 1.5 2.4 1.9 6.1H0V9.6H2C2 
                  12.7 2 15.8 2 18.9C3.3 18.9 4.6 18.9 5.8 18.9C5.8 15.8 5.8 12.7 5.8 9.6H8.7V6.1H5.8C5.8 5.1 5.8 3.7 6.3 3.4Z"/>
                </svg>
              </a>
            </li>
            <li class="footer-social__item">
              <a class="footer-social__link" href="https://www.youtube.com">
                <svg class="footer__logo-svg" width="20" height="14" viewBox="0 0 20 14" fill="none"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M17.1 0H2.8C1.3 0 0 1.3 0 2.8V11.1C0 12.7 1.3 14 2.8 14H17.1C18.7 
                  14 19.9 12.7 19.9 11.2V2.8C20 1.3 18.7 0 17.1 0ZM7 10.4V3.6L13.8 7L7 10.4Z"/>
                </svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
    <script src="{% static 'js/base_script.js' %}"></script>
  </body>
</html>